---
title: "PERMANOVA"
author: "NGG"
output: html_document
---

# 1. Load libraries

```{r}
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(vegan)))
```

# 2. Import data

```{r}
# Import data

# Feature_correspondence
features <- read.csv("../featureCorrespondence_MS2.csv", row.names = 1)
features <- as.data.frame(t(features))
# distance matrix - bray
dm <- vegdist(features, method="bray")

# Metadata
metadata <- read.csv("../../0_metadata/phenotypic_data.csv")
metadata$SampleCode <- gsub("-", '.', metadata$SampleCode, fixed = T)
```

# 3. PERMANOVA

Permutational Multivariate Analysis of Variance Using Distance Matrices
?adonis

Sources: https://rdrr.io/rforge/vegan/man/adonis.html, https://rpubs.com/collnell/manova

```{r}
set.seed(456)
permanova <- adonis(dm ~ Treatment + Time, 
                    data=metadata, 
                    permutations=999, 
                    method="bray")
permanova
# no reps in this example, so no significance...
filename <- paste0("permanova_results.csv")
write.csv(as.data.frame(permanova$aov.tab), filename)
```

Which taxa/feature contribute most to the community differences?

https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/multivariate-comparisons-of-microbial-community-composition.html

```{r}
test <- "Trt."
set.seed(456)
# LEAFLIFE; adonis tests homogeneity of dispersion among groups
p.Trt <- adonis(features ~ Treatment, data=metadata, permutations=999, method="bray")
p.Trt
## Interpretation:
# The R-square value is the important statistic for interpreting Adonis as it gives you the effect size. For example an R-squared of 0.44 means that 44% of the variation in distances is explained by the grouping being tested. The p value tells you whether or not this result was likely a result of chance. A p value of 0.05 means that there is a 5% chance that you detected a difference between groups (however large or small) when indeed there was none (the null hypothesis). 

############# extract coefficients for Feature representation
# to get coefficients supply the features df instead of the matrix dm
# matrix of coefficients of the linear model, with rows representing sources of variation and columns representing species; each column represents a fit of a species abundance to the linear model. These are what you get when you fit one species to your predictors.
p.Trt.features <- coefficients(p.Trt)['Treatment1',]
p.Trt.features <- p.Trt.features[rev(order(abs(p.Trt.features )))]
p.Trt.features <- as.data.frame(p.Trt.features) 
colnames(p.Trt.features) <- paste0(test, 'f.contrib')
p.Trt.features <- signif(p.Trt.features, 2)
p.Trt.features$Features <- rownames(p.Trt.features)
# filename <- paste0("features_contribution_Treatment.csv")
# write.csv(p.Trt.features, filename)
```

NEGATIVE == DRIVING INOCULUM
POSITIVE == DRIVING CONTROL

# 4. Feature Contribution

```{r}
t2 = quantile(abs(p.Trt.features$Trt.f.contrib), 0.60)
t2

p.Trt.features.g <- mutate(p.Trt.features,
                            Group = if_else(abs(Trt.f.contrib)<t2, 'low contribution',
                                                if_else(Trt.f.contrib>t2, 'Control', 'Inoculum')))

write.csv(p.Trt.features.g, "features_contribution_Group_Treatment.csv", row.names = F)

trt.contrib <- 
  p.Trt.features.g %>% 
  filter(abs(Trt.f.contrib)>t2) %>% 
  ggplot(aes(x = reorder(Features, Trt.f.contrib), y = Trt.f.contrib, fill = Trt.f.contrib > 0)) +
    geom_bar(stat="identity", width = 1, color='black', size=0.1, alpha=0.6) + 
    ylab("Contribution") +
    xlab("MS Features") +
    ggtitle(paste0("Contribution of features to Treatment")) +
    scale_fill_manual(values = c('#117733', '#AA3377'), labels = c('Inoculum', 'Control')) +
    # geom_hline(yintercept = t2, color = '#AA3377', size=0.5) +
    # geom_hline(yintercept = - t2, color = '#117733', size=0.5) +
    # scale_color_manual(values = list_of_colors) +
    # coord_flip() +
    theme_linedraw(base_size = 8) +
    theme(
      legend.title = element_blank(),
      legend.position = "top",
      legend.key.size = unit(0.3, 'cm'),
        # axis.text.y = element_blank(),
        # axis.ticks.y = element_blank(),
        panel.grid.major.x = element_blank(),
        # panel.grid.minor.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()
    ) 

trt.contrib
ggsave('Ft_Contribution_barplot.png',units=c('in'), width=6, height=4, dpi=300, trt.contrib)
```




```{r}
# # total features
# nfeatures = dim(p.Trt.features.g)[1]
# 
# # annotations
# ctrl <- p.Trt.features.g %>% filter(Trt.f.contrib > t2)
# n.ctrl <- dim(ctrl)[1]
# 
# inoc <- p.Trt.features.g %>% filter(Trt.f.contrib < -t2)
# n.inoc <- dim(inoc)[1]

# total <- paste0(nfeatures,' features detected in total.')
# upfeatures <- paste0(n.ctrl,' driving Brevideciduous.')
# downfeatures <- paste0(n.inoc,' driving Deciduous.')
# 
# total; upfeatures; downfeatures

# ft_count <- p.Trt.features.g %>% 
#   group_by(Group) %>% 
#   count()

# n.f.ctrl <- pull(ft_count[ft_count$Group=='Control', "n"])
# n.f.inoc <- pull(ft_count[ft_count$Group=='Inoculum', "n"])
```

